version: '2'
services:
  web:
    build: ../../images/alpine/nginx
    volumes_from:
      - container:vbase
    ports:
      - 80:80
      - 443:443
    links:
      - phpfpm:php56-fpm
      - esearch:search
      - mysql:db
  phpfpm:
    image: php:5.6-fpm-alpine
    volumes_from:
      - container:vbase
  esearch:
    image: elasticsearch:1.7-alpine
    ports:
      - 9200:9200
      - 9300:9300
  mysql:
    image: percona:5.6
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
