version: '2'
services:
  web:
    build: ../../images/alpine/httpd-php56
    volumes_from:
      - container:vbase
    links:
      - esearch:search
      - mysql:db
    ports:
      - 80:80
      - 443:443
  esearch:
    image: elasticsearch:1.7-alpine
    ports:
      - 9200:9200
      - 9300:9300
  mysql:
    image: percona:5.6
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
